global:
  ingress:
    hostname: prod-ingress.markdavison.kiwi
    certIssuer: letsencrypt-staging
api:
  app: zeno-fanfic-api
  replicas: 1
  name: zeno-fanfic-api
  image: ghcr.io/markrdavison/markdavison-berlin-api
  tag: v0.0.44
  port: 50000
  ingress:
    host: fanfic-api.markdavison.kiwi
  env:
    secret:
      - AUTH__CLIENT_SECRET
      - DATABASE__DB_USERNAME
      - DATABASE__DB_PASSWORD
      - REDIS__PASSWORD
      - NOTIFICATIONS__MATRIX__USERNAME
      - NOTIFICATIONS__MATRIX__PASSWORD
    public:
      BERLIN__AUTH__CLIENT_ID: zeno-berlin
      BERLIN__AUTH__SESSION_NAME: zeno-berlin-prod-session
      BERLIN__AUTH__SCOPE: openid profile email offline_access
      BERLIN__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      BERLIN__CLAIMS__OIDC_ID_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
      BERLIN__CLAIMS__OIDC_EMAIL_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      BERLIN__CLAIMS__OIDC_FIRST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
      BERLIN__CLAIMS__OIDC_LAST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
      BERLIN__CLAIMS__OIDC_USERNAME_ATTRIBUTE: preferred_username
      BERLIN__DATABASE__DATABASE_TYPE: postgres
      BERLIN__DATABASE__DB_DATABASE: fanfic
      BERLIN__DATABASE__DB_PORT: 5432
      BERLIN__DATABASE__DB_HOST: postgres.markdavison.kiwi
      BERLIN__REDIS__HOST: redis.markdavison.kiwi
      BERLIN__AO3__RATE_DELAY: 4
      BERLIN__NOTIFICATIONS__CONSOLE__ENABLED: true
      BERLIN__NOTIFICATIONS__MATRIX__ENABLED: true
      BERLIN__NOTIFICATIONS__MATRIX__URL: https://matrix-client.matrix.org
      BERLIN__NOTIFICATIONS__MATRIX__ROOMID: '!miNmGSGPmCyiGcKdKD:matrix.org'
      BERLIN__NOTIFICATIONS__MATRIX__SESSIONNAME: zeno-fanfic
      BERLIN__JOBS__JOB_CHECK_EVENT_KEY: jobeventkeyberlinproduction
      BERLIN__PRODUCTION_MODE: true
      BERLIN__URL: http://0.0.0.0:50000
apijobs:
  app: zeno-fanfic-api-jobs
  replicas: 1
  name: zeno-fanfic-api-jobs
  image: ghcr.io/markrdavison/markdavison-berlin-api-jobs
  tag: v0.0.44
  port: 50001
  env:
    secret:
      - DATABASE__DB_USERNAME
      - DATABASE__DB_PASSWORD
      - REDIS__PASSWORD
      - NOTIFICATIONS__MATRIX__USERNAME
      - NOTIFICATIONS__MATRIX__PASSWORD
    public:
      BERLIN__DATABASE__DATABASE_TYPE: postgres
      BERLIN__DATABASE__DB_DATABASE: fanfic
      BERLIN__DATABASE__DB_PORT: 5432
      BERLIN__DATABASE__DB_HOST: postgres.markdavison.kiwi
      BERLIN__REDIS__HOST: redis.markdavison.kiwi
      BERLIN__NOTIFICATIONS__CONSOLE__ENABLED: true
      BERLIN__NOTIFICATIONS__MATRIX__ENABLED: true
      BERLIN__NOTIFICATIONS__MATRIX__URL: https://matrix-client.matrix.org
      BERLIN__NOTIFICATIONS__MATRIX__ROOMID: '!miNmGSGPmCyiGcKdKD:matrix.org'
      BERLIN__NOTIFICATIONS__MATRIX__SESSIONNAME: zeno-fanfic
      BERLIN__JOBS__JOB_CHECK_EVENT_KEY: jobeventkeyberlinproduction
      BERLIN__PRODUCTION_MODE: true
      BERLIN__JOB_URL: http://0.0.0.0:50001
apiorchestrator:
  app: zeno-fanfic-api-orchestrator
  replicas: 1
  name: zeno-fanfic-api-orchestrator
  image: ghcr.io/markrdavison/markdavison-berlin-api-orchestrator
  tag: v0.0.44
  port: 50001
  env:
    secret:
      - DATABASE__DB_USERNAME
      - DATABASE__DB_PASSWORD
      - REDIS__PASSWORD
    public:
      BERLIN__DATABASE__DATABASE_TYPE: postgres
      BERLIN__DATABASE__DB_DATABASE: fanfic
      BERLIN__DATABASE__DB_PORT: 5432
      BERLIN__DATABASE__DB_HOST: postgres.markdavison.kiwi
      BERLIN__REDIS__HOST: redis.markdavison.kiwi
      BERLIN__JOBS__JOB_CHECK_EVENT_KEY: jobeventkeyberlinproduction
      BERLIN__STORIES_PER_CRON_UPDATE: 20
      BERLIN__JOB_CHECK_RATE: '*/15 * * * *'
      BERLIN__MONTHLY_STORY_NOTIFICATIONS_RATE: 0 8 1,15 * *
      BERLIN__STORY_UPDATE_RATE: 0 */3 * * *
      BERLIN__CRON_TIMEZONE: LOCAL
      BERLIN__PRODUCTION_MODE: true
bffweb:
  app: zeno-fanfic-bff
  replicas: 1
  name: zeno-fanfic-bff
  image: ghcr.io/markrdavison/markdavison-berlin-bff-web
  tag: v0.0.44
  port: 40000
  ingress:
    host: fanfic-bff.markdavison.kiwi
  env:
    secret:
      - REDIS__PASSWORD
      - AUTH__CLIENT_SECRET
      - AUTH__SESSION_SECRET
    public:
      BERLIN__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      BERLIN__AUTH__CLIENT_ID: zeno-berlin
      BERLIN__AUTH__SESSION_NAME: zeno-berlin-prod-session
      BERLIN__AUTH__SCOPE: openid profile email offline_access
      BERLIN__CLAIMS__OIDC_ID_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
      BERLIN__CLAIMS__OIDC_EMAIL_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      BERLIN__CLAIMS__OIDC_FIRST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
      BERLIN__CLAIMS__OIDC_LAST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
      BERLIN__CLAIMS__OIDC_USERNAME_ATTRIBUTE: preferred_username
      BERLIN__REDIS__HOST: redis.markdavison.kiwi
      BERLIN__WEB_ORIGIN: https://fanfic.markdavison.kiwi
      BERLIN__BFF_ORIGIN: https://fanfic-bff.markdavison.kiwi
      BERLIN__API_ORIGIN: https://fanfic-api.markdavison.kiwi
      BERLIN__PRODUCTION_MODE: true
      BERLIN__URL: http://0.0.0.0:40000
web:
  app: zeno-fanfic-web
  replicas: 1
  name: zeno-fanfic-web
  image: ghcr.io/markrdavison/markdavison-berlin-web
  tag: v0.0.44
  port: 80
  ingress:
    host: fanfic.markdavison.kiwi
  env:
    secret: []
    public:
      WEB_PORT: '80'
      BFF_BASE_URI: https://fanfic-bff.markdavison.kiwi
