global:
  ingress:
    hostname: prod-ingress.markdavison.kiwi
    certIssuer: letsencrypt-staging
api:
  app: zeno-fanfic-api
  replicas: 1
  name: zeno-fanfic-api
  image: ghcr.io/markrdavison/markdavison-berlin-api
  tag: v0.0.12
  port: 50000
  ingress:
    host: fanfic-api.markdavison.kiwi
  env:
    secret:
      - AUTH__CLIENT_SECRET
      - DATABASE__DB_USERNAME
      - DATABASE__DB_PASSWORD
    public:
      BERLIN__DATABASE__DATABASE_TYPE: postgres
      BERLIN__DATABASE__DB_DATABASE: fanfic
      BERLIN__DATABASE__DB_PORT: 5432
      BERLIN__DATABASE__DB_HOST: postgres.markdavison.kiwi
      BERLIN__URL: http://0.0.0.0:50000
      BERLIN__AUTH__CLIENT_ID: zeno-berlin
      BERLIN__AUTH__SESSION_NAME: zeno-berlin-prod-session
      BERLIN__AUTH__SCOPE: openid profile email offline_access zeno-berlin
      BERLIN__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      BERLIN__PRODUCTION_MODE: true
bffweb:
  app: zeno-fanfic-bff
  replicas: 1
  name: zeno-fanfic-bff
  image: ghcr.io/markrdavison/markdavison-berlin-bff-web
  tag: v0.0.12
  port: 40000
  ingress:
    host: fanfic-bff.markdavison.kiwi
  env:
    secret:
      - REDIS__PASSWORD
      - AUTH__CLIENT_SECRET
      - AUTH__SESSION_SECRET
    public:
      BERLIN__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      BERLIN__REDIS__PORT: '6379'
      BERLIN__WEB_ORIGIN: https://fanfic.markdavison.kiwi
      BERLIN__BFF_ORIGIN: https://fanfic-bff.markdavison.kiwi
      BERLIN__API_ORIGIN: https://fanfic-api.markdavison.kiwi
      BERLIN__AUTH__SESSION_NAME: zeno-berlin-prod-session
      BERLIN__REDIS__HOST: redis.markdavison.kiwi
      BERLIN__AUTH__CLIENT_ID: zeno-berlin
      BERLIN__URL: http://0.0.0.0:40000
      BERLIN__AUTH__SCOPE: openid profile email offline_access zeno-berlin
      BERLIN__PRODUCTION_MODE: true
web:
  app: zeno-fanfic-web
  replicas: 1
  name: zeno-fanfic-web
  image: ghcr.io/markrdavison/markdavison-berlin-web
  tag: v0.0.12
  port: 80
  ingress:
    host: fanfic.markdavison.kiwi
  env:
    secret: []
    public:
      WEB_PORT: '80'
      BFF_BASE_URI: https://fanfic-bff.markdavison.kiwi
