global using mark.davison.berlin.shared.constants;
global using mark.davison.berlin.shared.logic.Settings;
global using mark.davison.berlin.shared.logic.StoryInfo;
global using mark.davison.common.abstractions.Services;
global using mark.davison.common.test;
global using mark.davison.common.Utility;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
